language: java
jdk: 
  - oraclejdk8

install:
  - ant

script:
  - git config --global push.default simple
  - export GIT_TAG=$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
  - ant build

  skip_cleanup: true
  on:
    tags: false
    all_branches: true