language: java
install: ant deps

jobs:
  script: 
    - cd $TRAVIS_BUILD_DIR/Ferengi-Pizza
    - export GIT_TAG=$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
    - ant clean
    - ant compile
    - ant jar
    - ant run

